[package]
name = "kani-cmd"
version = "0.1.0"
authors = ["YLStax <kan1.921017@gmail.com>"]
edition = "2018"

[dependencies]
kani-evaluator = { version = "0.1.0", path = "../kani-evaluator" }
clap = "2.33.3"
