[package]
name = "kani-evaluator"
version = "0.2.0"
authors = ["YLStax <kan1.921017@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kani-parser = { version = "0.2.0", path = "../kani-parser" }
