[package]
name = "kani-repl"
version = "0.2.0"
authors = ["YLStax <kan1.921017@gmail.com>"]
edition = "2018"

[dependencies]
kani-evaluator = { version = "0.2.0", path = "../kani-evaluator" }
rustyline = "7.1.0"
rustyline-derive = "0.4.0"
